### ISSUE TITLE
Blocking tmpl= in query string causes problems

### ISSUE THREAD

**Issue by ercanozkaya** [nikosdion/master-htaccess#1]
Hi Nicholas,

In Nooku Framework we are using tmpl=koowa to provide another layout in addition to component and system. This lets us control the full HTML output in certain parts like popup windows.

The below code breaks this by only allowing tmpl=system or tmpl=component:
https://github.com/nikosdion/master-htaccess/blob/master/htaccess.txt#L341

This rule does not stop people from fingerprinting Joomla sites either as any URL can still be accessed with tmpl=component.

Would you be interested in a PR to remove this restriction?

Thanks,
Ercan

**Comment by filipe-torres** [comment]
Hi Nicholas,
The code below breaks popup windows opened by **Print** and **E-mail** buttons (popups return 404 error) in category blog and articles views (com_content component):
https://github.com/nikosdion/master-htaccess/blob/master/htaccess.txt#L339

This error gone way when I removed `component|` string from above line.

The code below causes same error only in **E-mail** button:
https://github.com/nikosdion/master-htaccess/blob/master/htaccess.txt#L341

This error gone way when I removed `|emplate` string from above line.

You can see both errors in action at: http://abladvogados.com.br/areas-de-atuacao/30-institucional/areas-de-atuacao/direito-administrativo/18-licitacoes

This errors occurs in Joomla 1.5, 2.5 and 3.0.

Thanks.

Filipe Torres

**Comment by nikosdion** [comment]
So, the problem is that it does what it says it does?

**Comment by filipe-torres** [comment]
No. The problem is that these rules prevent the proper functioning of Print and E-mail core buttons and correct functioning of the others components too (e.g.: Phoca Gallery).

Example: in website cited above I have this link for Print button: 
http://abladvogados.com.br/areas-de-atuacao/30-institucional/areas-de-atuacao/direito-administrativo/18-licitacoes?tmpl=component&print=1&page=
This link doesn't work because this line block the link:
https://github.com/nikosdion/master-htaccess/blob/master/htaccess.txt#L339

Can you help me to write a rule that creates an exception por specific links that have these query strings?

Thanks for your help.

Filipe Torres

**Comment by nikosdion** [comment]
Yes, I can. Please purchase Admin Tools Professional where this and other issues have been addressed three to four years ago.
